<?php

namespace App\Models;

use Spatie\Permission\Models\Permission as SpatiePermission;

class Permission extends SpatiePermission
{
    const CAN_VIEW_ADMIN = 1;
    const CAN_CREATE_ADMIN = 2;
    const CAN_EDIT_ADMIN = 3;
    const CAN_DELETE_ADMIN = 4;
    const HAS_ALL_ADMIN_ACCESS = 5;
    const CAN_VIEW_MANAGER = 6;
    const CAN_CREATE_MANAGER = 7;
    const CAN_EDIT_MANAGER = 8;
    const CAN_DELETE_MANAGER = 9;
    const HAS_ALL_MANAGERS_ACCESS = 10;
    const CAN_VIEW_AGENT = 11;
    const CAN_CREATE_AGENT = 12;
    const CAN_EDIT_AGENT = 13;
    const CAN_DELETE_AGENT = 14;
    const HAS_ALL_AGENT_ACCESS = 15;
    const CAN_VIEW_USER = 16;
    const CAN_CREATE_USER = 17;
    const CAN_EDIT_USER = 18;
    const CAN_DELETE_USER = 19;
    const HAS_ALL_USERS_ACCESS = 20;

    const CAN_VIEW_SALE_REPRESENTATIVE_USER = 21;
    const CAN_CREATE_SALE_REPRESENTATIVE_USER = 22;
    const CAN_EDIT_SALE_REPRESENTATIVE_USER = 23;
    const CAN_DELETE_SALE_REPRESENTATIVE_USER = 24;
    const HAS_ALL_SALE_REPRESENTATIVE_USERS_ACCESS = 25;

    const CAN_VIEW_ASSISTANT_SALE_MANAGER_USER = 26;
    const CAN_CREATE_ASSISTANT_SALE_MANAGER_USER = 27;
    const CAN_EDIT_ASSISTANT_SALE_MANAGER_USER = 28;
    const CAN_DELETE_ASSISTANT_SALE_MANAGER_USER = 29;
    const HAS_ALL_ASSISTANT_SALE_MANAGER_USERS_ACCESS = 30;

    const CAN_VIEW_SALE_MANAGER_USER = 31;
    const CAN_CREATE_SALE_MANAGER_USER = 32;
    const CAN_EDIT_SALE_MANAGER_USER = 33;
    const CAN_DELETE_SALE_MANAGER_USER = 34;
    const HAS_ALL_SALE_MANAGER_USERS_ACCESS = 35;

    const CAN_VIEW_BUSINESS_MANAGER_USER = 36;
    const CAN_CREATE_BUSINESS_MANAGER_USER = 37;
    const CAN_EDIT_BUSINESS_MANAGER_USER = 38;
    const CAN_DELETE_BUSINESS_MANAGER_USER = 39;
    const HAS_ALL_BUSINESS_MANAGER_USERS_ACCESS = 40;

    const CAN_VIEW_GROUP_MANAGER_USER = 41;
    const CAN_CREATE_GROUP_MANAGER_USER = 42;
    const CAN_EDIT_GROUP_MANAGER_USER = 43;
    const CAN_DELETE_GROUP_MANAGER_USER = 44;
    const HAS_ALL_GROUP_MANAGER_USERS_ACCESS = 45;

    const CAN_VIEW_ZONAL_MANAGER_USER = 46;
    const CAN_CREATE_ZONAL_MANAGER_USER = 47;
    const CAN_EDIT_ZONAL_MANAGER_USER = 48;
    const CAN_DELETE_ZONAL_MANAGER_USER = 49;
    const HAS_ALL_ZONAL_MANAGER_USERS_ACCESS = 50;

    const CAN_VIEW_REGIONAL_MANAGER_USER = 51;
    const CAN_CREATE_REGIONAL_MANAGER_USER = 52;
    const CAN_EDIT_REGIONAL_MANAGER_USER = 53;
    const CAN_DELETE_REGIONAL_MANAGER_USER = 54;
    const HAS_ALL_REGIONAL_MANAGER_USERS_ACCESS = 55;

    const CAN_VIEW_NATIONAL_SALE_DIRECTOR_USER = 56;
    const CAN_CREATE_NATIONAL_SALE_DIRECTOR_USER = 57;
    const CAN_EDIT_NATIONAL_SALE_DIRECTOR_USER = 58;
    const CAN_DELETE_NATIONAL_SALE_DIRECTOR_USER = 59;
    const HAS_ALL_NATIONAL_SALE_DIRECTOR_USERS_ACCESS = 60;

    /**
     *
     * remaining ids are dedicated for user roles (60 - 500)
     */

    const CAN_VIEW_PRODUCT = 501;
    const CAN_CREATE_PRODUCT = 502;
    const CAN_EDIT_PRODUCT = 503;
    const CAN_DELETE_PRODUCT = 504;
    const HAS_ALL_PRODUCTS_ACCESS = 505;

    const CAN_VIEW_LOCATION = 506;
    const CAN_CREATE_LOCATION = 507;
    const CAN_EDIT_LOCATION = 508;
    const CAN_DELETE_LOCATION = 509;
    const HAS_ALL_LOCATIONS_ACCESS = 510;

    const CAN_VIEW_ORDER = 511;
    const CAN_CREATE_ORDER = 512;
    const CAN_EDIT_ORDER = 513;
    const CAN_DELETE_ORDER = 514;
    const HAS_ALL_ORDERS_ACCESS = 515;

    const CAN_VIEW_COMMISSION = 516;
    const CAN_CREATE_COMMISSION = 517;
    const CAN_EDIT_COMMISSION = 518;
    const CAN_DELETE_COMMISSION = 519;
    const HAS_ALL_COMMISSIONS_ACCESS = 520;

    const CAN_VIEW_FILE = 521;
    const CAN_UPLOAD_FILE = 522;
    const CAN_EDIT_FILE = 523;
    const CAN_DELETE_FILE = 524;
    const HAS_ALL_FILES_ACCESS = 525;
}
