export const PRODUCT_STATUSES = {
    PRODUCT_STATUS_DRAFT: 0,
    PRODUCT_STATUS_PUBLISHED: 1,
    PRODUCT_STATUS_TRASHED: 3
}


export const PRODUCT_TYPES = {
    PRODUCT_TYPE_UNCATEGORIZED: 1,
    PRODUCT_TYPE_SIMPLE: 2,
    PRODUCT_TYPE_VARIABLE: 3,
    PRODUCT_TYPE_EXTERNAL: 4,
    PRODUCT_TYPE_GROUPED: 5
};

export const PRODUCT_PROPERTY = {
    TYPE_PROPERTY: 1,
    TYPE_FLAT: 2,
    TYPE_BOOK: 3
};
